#!/bin/bash
echo "🧹 Cleaning build files before push..."
make clean

msg=${1:-"update"}
echo "📤 Pushing to repository..."
git add .
git commit -m "$msg"
git push origin $(git rev-parse --abbrev-ref HEAD)
echo "✅ Push complete!"

